note_app_showcase/models/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import mapped_column, relationship


db = SQLAlchemy()

class User(db.Model):
    id = mapped_column(db.Integer, primary_key=True)
    username = mapped_column(db.String(50), unique=True, nullable=False)
    password = mapped_column(db.String(100), nullable=False)
    notes = relationship('Note', backref='user', lazy=True)

class Note(db.Model):
    id = mapped_column(db.Integer, primary_key=True)
    title = mapped_column(db.String(100), nullable=False)
    content = mapped_column(db.Text, nullable=False)
    user_id = mapped_column(db.Integer, db.ForeignKey('user.id'), nullable=False)

note_app_showcase/app.py
from flask import Flask
from models.models import db
from flask_wtf.csrf import CSRFProtect

app = Flask(__name__)

app.secret_key = "fdasjghfkzrytsadhfgkjas"

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///notes.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

csrf = CSRFProtect(app)



from views.login import bp as bp_login
app.register_blueprint(bp_login)

from views.notes import bp as bp_notes
app.register_blueprint(bp_notes)

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)

note_app_showcase/views/login.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import check_password_hash, generate_password_hash
from models.models import db, User
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

bp = Blueprint('login_bp', __name__)

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            session['username'] = user.username
            return redirect(url_for('notes_bp.notes'))
        else:
            return render_template('login.html', form=form, error="Invalid username or password.")
    
    return render_template('login.html', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        # Check if the username already exists
        if User.query.filter_by(username=username).first():
            return render_template('register.html', form=form, error="Username already exists.")

        # Create a new user
        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        
        return redirect(url_for('login_bp.login'))
    
    return render_template('register.html', form=form)

@bp.route('/logout')
def logout():
    # Remove user information from the session
    session.pop('user_id', None)
    session.pop('username', None)
    return redirect(url_for('login_bp.login'))

note_app_showcase/views/notes.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.csrf import CSRFProtect

from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models.models import Note, db

bp = Blueprint('notes_bp', __name__)


@bp.route('/')
def notes():
    user_id = session.get('user_id')
    if user_id:
        notes = Note.query.filter_by(user_id=user_id).all()
        return render_template('notes.html', notes=notes)
    else:
        flash('Musisz być zalogowany żeby przeglądać notatki', 'error')
        return redirect(url_for('login_bp.login'))


@bp.route('/add_note', methods=['GET', 'POST'])
def add_note():

    class AddNoteForm(FlaskForm):
        title = StringField('Title', validators=[DataRequired()])
        content = TextAreaField('Content', validators=[DataRequired()])
        submit = SubmitField('Add Note')
    
    form = AddNoteForm()
    
    if form.validate_on_submit():
        user_id = session.get('user_id')
        if user_id:
            title = form.title.data
            content = form.content.data
            
            new_note = Note(title=title, content=content, user_id=user_id)
            db.session.add(new_note)
            db.session.commit()
            flash('Dodano notatkę', 'success')
            return redirect(url_for('notes_bp.notes'))
        else:
            flash('Musisz być zalogowany żeby dodawać notatki', 'error')
            return redirect(url_for('login_bp.login'))
    return render_template('add_note.html', form=form)


@bp.route('/edit_note/<int:note_id>', methods=['GET', 'POST'])
def edit_note(note_id):

    class EditNoteForm(FlaskForm):
        title = StringField('Title', validators=[DataRequired()])
        content = TextAreaField('Content', validators=[DataRequired()])
        submit = SubmitField('Update Note')
    
    form = EditNoteForm()
    note = Note.query.get_or_404(note_id)

    if form.validate_on_submit():
        note.title = form.title.data
        note.content = form.content.data
        db.session.commit()
        flash('Note updated successfully', 'success')
        return redirect(url_for('notes_bp.notes'))
    elif request.method == 'GET':
        form.title.data = note.title
        form.content.data = note.content 

    return render_template('edit_note.html', form=form)

@bp.route('/delete_note/<int:note_id>', methods=['POST'])
def delete_note(note_id):
    user_id = session.get('user_id')
    if user_id:
        note = Note.query.get_or_404(note_id)
        db.session.delete(note)
        db.session.commit()
    else:
        flash('Usunięto notatkę', 'error')
        return redirect(url_for('login_bp.login'))
    return redirect(url_for('notes_bp.notes'))

note_app_showcase/templates/add_note.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Note</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container mt-5">
        <h1>Dodaj nową notatkę</h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title.label }}
                {{ form.title(class="form-control") }}
                {% for error in form.title.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.content.label }}
                {{ form.content(class="form-control") }}
                {% for error in form.content.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary") }}
        </form>
    </div>
</body>

</html>

note_app_showcase/templates/edit_note.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Note</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container mt-5">
        <h1>Edit Note</h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title.label(class="form-label") }}
                {{ form.title(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-label") }}
                {{ form.content(class="form-control") }}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</body>

</html>

note_app_showcase/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container mt-5">
        <div class="jumbotron" style="background-color: rgb(233, 233, 233);">
            <h2 class="display-4" style="font-family:'Gill Sans';color: rgb(105, 145, 160);font-weight: 700;">Wybitna
                aplikacja do robienia notatek</h2>
            {% if error %}
            <p class="text-danger">{{ error }}</p>
            {% endif %}
            <p class="lead">Zaloguj się by uzyskać dostęp :)</p>
            <hr class="my-4">
            <form method="POST" action="/login">
                {{ form.hidden_tag() }} {# Include CSRF token #}
                <div class="form-group">
                    <label for="username">Nazwa użytkownika:</label>
                    {{ form.username(class="form-control", id="username") }} {# Render username field #}
                </div>
                <div class="form-group">
                    <label for="password">Hasło:</label>
                    {{ form.password(class="form-control", id="password") }} {# Render password field #}
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <p class="mt-3">Nie masz konta? -> <a href="/register">Zarejestruj się!</a></p>
        </div>
    </div>
</body>

</html>

note_app_showcase/templates/notes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notes</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .note-card {
            margin-bottom: 20px;
            background-color: rgb(241, 238, 227);
            position: relative;
            padding-bottom: 50px;
            /* Add padding to the bottom to prevent overlap */
        }

        .note-card .card-body {
            padding: 20px;
        }

        .edit-btn {
            position: absolute;
            top: 20px;
            right: 20px;
        }

        .delete-btn {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h1 style="margin-bottom: 40px;">Twoje notatki:</h1>
        <div class="row">
            {% for note in notes %}
            <div class="col-md-12">
                <div class="card note-card">
                    <div class="card-body">
                        <h4 class="card-title" style="color: rgb(51, 43, 19); font-weight: 700;">{{ note.title }}</h5>
                            <hr>
                            <p class="card-text">{{ note.content }}</p>
                    </div>
                    <form method="GET" action="{{ url_for('notes_bp.edit_note', note_id=note.id) }}" class="edit-btn">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-secondary" style="width: 100px;">Edytuj</button>
                    </form>
                    <form method="POST" action="{{ url_for('notes_bp.delete_note', note_id=note.id) }}"
                        class="delete-btn">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-danger" style="width: 75px;">Usuń</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
        <hr>
        <a href="{{ url_for('notes_bp.add_note') }}" class="btn btn-success d-block mx-auto" style="width: 300px;">Dodaj nową notatkę</a>
        <a href="{{ url_for('login_bp.logout') }}" class="btn btn-primary"
            style="position: absolute; right:50px; top: 50px">Wyloguj</a>
    </div>
</body>

</html>

note_app_showcase/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container mt-5">
        <div class="jumbotron" style="background-color: rgb(255, 255, 255)">
            <h1 class="display-4">Rejestracja</h1>
            {% if error %}
            <p class="text-danger">{{ error }}</p>
            {% endif %}
            <p class="lead">Stwórz nowe konto.</p>
            <hr class="my-4">
            <form method="POST" action="/register">
                {{ form.hidden_tag() }} {# Include CSRF token #}
                <div class="form-group">
                    <label for="username">Nazwa użytkownika:</label>
                    {{ form.username(class="form-control", id="username") }} {# Render username field #}
                </div>
                <div class="form-group">
                    <label for="password">Hasło:</label>
                    {{ form.password(class="form-control", id="password") }} {# Render password field #}
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
            <p class="mt-3">Masz już konto? -> <a href="/login">Zaloguj się!</a></p>
        </div>
    </div>
</body>

</html>